type: reference-docs
definitionId: abcCheckout
settings:
  pagination: section
  showConsole: true
  jsonSampleExpandLevel: 'all'
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: JavaScript
      - lang: Node.js
